### ISSUE TITLE
Unable to move cards #bug

### ISSUE THREAD

**Issue by museburg** [ycnmhd/obsidian-lineage#10]
Thank you very much for developing such an Obsidian plugin! It helps a lot.
However, I noticed a bug recently. When I try to drag and move a card, the page automatically scrolls down, and it only goes back to normal when I exit the page and reopen it. I recorded a video to show the bug.

https://github.com/ycnmhd/obsidian-lineage/assets/59810944/000652a6-0199-4b64-93f6-e76fbe6ac302

To make it easier for you to troubleshoot the bug, my information is attached.
OS: Windows 11 23H2
Obsidian: v1.5.12 (newest)
Lineage: v0.4.0-dev (newest)

**Comment by ycnmhd** [comment]
This bug has been fixed in version [0.5.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.5.0-dev)
