### ISSUE TITLE
Theme colors should support dark and light modes to define different colors

### ISSUE THREAD

**Issue by michaellw** [ycnmhd/obsidian-lineage#13]
The current theme colour definitions don't fit dark/light modes perfectly at the same time, text can be difficult to read due to background colour mismatch.
![2024-04-29_08-53-09](https://github.com/ycnmhd/obsidian-lineage/assets/276357/0975edb9-8972-46fb-9711-13a94a2f38d1)

**Comment by ycnmhd** [comment]
Will be fixed in the next version.
As a temporary solution, you can use the Reset button in Settings to apply the default color of the active theme

**Comment by ycnmhd** [comment]
Fixed in [0.5.1](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.5.1) (you might need to reset colors one last time)
