### ISSUE TITLE
Using keyboard shortcuts to open links under cursor is not working

### ISSUE THREAD

**Issue by ulahcherubim** [ycnmhd/obsidian-lineage#22]
First of all, thank you for this amazing plugin. Although it is in beta, I think it is pretty stable and not resource sensitive, which is a great accomplishment by your effort. This plugin transformed my workflow and made Obsidian visually organizable without the need for various tweaks.

I am not able to use Ctrl+Enter or Ctrl+Alt+Enter commands to open the link unders cursor in new tab or in the same tab. If you need further information or debug output to resolve this, please let me know.

**Comment by ycnmhd** [comment]
Thank you for your feedback. I'll look into it.
