### ISSUE TITLE
Convert or export to outline format

### ISSUE THREAD

**Issue by imed-ghomari** [ycnmhd/obsidian-lineage#26]
Hi, thank you for your contribution.

I would like to know if it's possible to have the plugin work with a normal outline format. Ideally, it would be able to convert an existing outline to the plugin's format. Even better would be if the plugin could work with the outline format by default, so that when I toggle the normal file view, I would see an outline instead of the current format. This would help improve compatibility with Markdown.

**Comment by Quorafind** [comment]
If the developer permits, I would be able to contribute some work on this issue. But maybe it would be diffcult to control which mode should be apply to current view. 

If parsing from outliner is available, maybe lineage have to add a type or other property to mark current file view mode (for example: `lineage: section ` or `lineage: outliner`

**Comment by ycnmhd** [comment]
@Quorafind  Absolutely, but please make sure to use the existing abstractions, and to add unit tests for functions that transform/mutate data ([example1](https://github.com/ycnmhd/obsidian-lineage/blob/master/src/stores/view/helpers/json-to-md/json-to-makdown/data/ginkgo_acedemic_paper.ts), [example 2](https://github.com/ycnmhd/obsidian-lineage/blob/8200841f8a88001c3cfbb923bda926ef65f30e7e/src/stores/document/reducers/delete-node/delete-node.spec.ts#L6))

> maybe lineage have to add a type or other property to mark

View type could be saved in [settings.documents](https://github.com/ycnmhd/obsidian-lineage/blob/8200841f8a88001c3cfbb923bda926ef65f30e7e/src/stores/settings/settings-type.ts#L32) property

**Comment by ycnmhd** [comment]
Added in [0.6.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.6.0)
