### ISSUE TITLE
Editing note causes it to limit the card height even if I toggled it off

### ISSUE THREAD

**Issue by gvivster** [ycnmhd/obsidian-lineage#30]
The setting is still off when this happens.
![image](https://github.com/ycnmhd/obsidian-lineage/assets/63889272/2e7da661-3d9f-45db-b701-98bbfb81feef)

**Comment by ycnmhd** [comment]
Limiting the editor height is intentional, otherwise it interferes with vertical scrolling (when the caret is offscreen)

**Comment by ycnmhd** [comment]
Fixed in 0.6.0
