### ISSUE TITLE
Automatic Indentation Based on Headers

### ISSUE THREAD

**Issue by alitekdemir** [ycnmhd/obsidian-lineage#33]
### What would you like to be added?

Currently, the plugin operates by creating <section-x> tags, but this process is quite cumbersome and manual for existing documents with many headers.

I would like to request a feature that allows the plugin to automatically create indents based on the headers. This would eliminate the need for users to manually adjust the existing header structures and make the plugin more efficient to use.

### Why is this feature needed?

This feature is needed because the current method of creating <section> tags is time-consuming and labor-intensive for documents with many headers. By automating the indentation process based on headers, users can save time and effort, and the plugin will be more user-friendly and efficient.

Thank you for considering this suggestion.

### Estimated usefulness for plugin users

Useful for the majority of users

**Comment by ycnmhd** [comment]
Good suggestion.
(As a less tedious, temporary process, you can use `split at cursor` and `move card` view hotkeys to breakdown the document)

**Comment by ycnmhd** [comment]
Added in [0.5.4](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.5.4)

**Comment by danieltomasz** [comment]
How to use/activate this option? I am on 0.5.4

**Comment by ycnmhd** [comment]
It's available as a card context-menu item
![2024-06-02_14-45-04](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/39d21a92-5161-4204-8360-3bd7c12e13ff)

**Comment by danieltomasz** [comment]
Thanks!

**Comment by oscaromsn** [comment]
Hi there!

I was just about to open a feature request after spending a while splitting headers manually using the `split at cursor` shortcut.

I know that this kind of feature makes more sense to be used on the context menu, but maybe also putting this option in the command palette would be great.

It may also be just a noob thing on my part, but I think that many Obsidian users are more keyboard-centric using keybindings and vim mode and right-clicking isn't as intuitive as looking at command palette options.

I think that commands like "convert current note to lineage document" and "clean lineage markup" may also be welcomed.

_Btw, amazing job — this plugin is awesome! I work with extensive legal documents and navigating between arguments and rearranging them was always a hassle. I had tried out many outline and mind-map apps, but none of them provided a smooth experience like this one did. I can say that you have changed my life forever 😄_

**Comment by alitekdemir** [comment]
When attempting to use the "split by headings" feature, I encounter the following error message:
`cannot read properties of undefined (reading 'group')`
The error message appears, and the document is not split.

https://github.com/ycnmhd/obsidian-lineage/assets/1507344/14f846be-61ad-4935-aeec-4445ad982257

md file:
[2 Key Project Management Terms.md](https://github.com/user-attachments/files/15534338/2.Key.Project.Management.Terms.md)

**Comment by ycnmhd** [comment]
@alitekdemir  The implementation expects first level heading to be H1.

**Comment by alitekdemir** [comment]
The Lineage Plugin should first correct issues with multiple `<h1>` tags and non-sequential heading levels. For example, if there is no `<h1>`, it can reference the highest-level heading available, and then correct any skips in the sequence (e.g., if there's a jump from `<h1>` to `<h3>`, it should change `<h3>` to `<h2>`). Alternatively, it could use the `<section>` tag while paying attention to the order of headings. I use the "Linter" plugin to ensure that headings are sequential.
Thank you for your efforts and attention.

**Comment by Droyk** [comment]
@ycnmhd Please work on @alitekdemir Suggestion! having the same problem.

**Comment by ycnmhd** [comment]
@Droyk I updated the implementation to correct headings before splitting.
If you want to use it before the next version is released, download `main.js` and place it in the plugin folder, then disable the plugin and re-enable it
[main.zip](https://github.com/user-attachments/files/15793676/main.zip)

**Comment by ycnmhd** [comment]
Here is the spec: https://github.com/ycnmhd/obsidian-lineage/blob/next/src/lib/data-conversion/helpers/correct-headings.spec.ts

**Comment by ycnmhd** [comment]
@alitekdemir Your recommendation has been implemented in [0.6.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.6.0)
