### ISSUE TITLE
Zooming doesn't work correctly in mobile/tablet app

### ISSUE THREAD

**Issue by itsame934** [ycnmhd/obsidian-lineage#34]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

When using the zoom function, especially with the keep cards in center options, the cards don't center properly on the screen. I think it's an issue with the overall zoom functionality, but I could be wrong.

In my case, when zooming out a few options, my cards appeared more and more to the lower left of the screen, making navigation really hard.

### What did you expect to happen?

I wanted the highlighted card to stay in the middle of the screen, regardless of the zoom.

### Relevant console output

no errors

### Obsidian version

Newest version

### OS

Other

**Comment by ycnmhd** [comment]
Fixed in [0.5.4](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.5.4)

**Comment by itsame934** [comment]
It works beautifully now, thanks a bunch!
