### ISSUE TITLE
Zoom to fit is zooming out (making card smaller)

### ISSUE THREAD

**Issue by danieltomasz** [ycnmhd/obsidian-lineage#36]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

Zoom to fit  button is zooming out the view

### What did you expect to happen?

"Zoom to fit" will maximalize cards to fit into screen

### Relevant console output

No output.

### Obsidian version

1.6.1

### OS

macOS

**Comment by ycnmhd** [comment]
Zoom to fit is meant to fit the entire document height into view 

> # What did you expect to happen?
> "Zoom to fit" will maximalize cards to fit into screen

Do you mean  both in preview and edit mode?

**Comment by danieltomasz** [comment]
I am in the live preview mode, I have only  1 card in my note, every time when I use zoom to fit it keeps getting smaller and smaller and it doesn't stop, the same way as zooming out behaviour

**Comment by ycnmhd** [comment]
Fixed in [0.6.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.6.0)
