### ISSUE TITLE
hotkeys to move around on the lineage view with the keyboard

### ISSUE THREAD

**Issue by LePenseur13** [ycnmhd/obsidian-lineage#37]
### What would you like to be added?

keyboard shortcuts to focus on:
- siblings (top and bottom)
- parent (left)
- child (right)

### Why is this feature needed?

increases usability, so the user does not have to switch constantly from keyboard to mouse. 

### Estimated usefulness for plugin users

Useful for many users

**Comment by ycnmhd** [comment]
Navigation hotkeys are available in `view-hotkeys `  (different from Obsidian hotkeys)
![image](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/a5cc23ce-b0eb-4925-914a-baca2cd4fde2)

**Comment by LePenseur13** [comment]
thank you that is helpful. 

Didn’t know.

Maybe it could be mentioned in the readme/documentation more clearly.
