### ISSUE TITLE
add support for multiple obsidian windows

### ISSUE THREAD

**Issue by edwardsayer** [ycnmhd/obsidian-lineage#40]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

1. Open a note in Lineage
2. Open current tab in new window
3. try to move around lineage views with arrow keys but it doesn't work

### What did you expect to happen?

Move around different lineage views with arrow keys should works just like it behaves in the main window.

### Obsidian version

1.6.3

### OS

Windows

**Comment by Bearsaerker** [comment]
This is still a bug in version 0.6.0
