### ISSUE TITLE
Compatible with another plugin typewriter-mode

### ISSUE THREAD

**Issue by calmwaves111** [ycnmhd/obsidian-lineage#41]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

I am using another plugin at the same time https://github.com/davisriedel/obsidian-typewriter-mode
When two plugins are turned on simultaneously, once I start typing, the input box will run to the top and I cannot see the text I am typing

### What did you expect to happen?

I hope that when typing text, the input box can automatically focus on the center of the screen
I'm not sure if this is a problem with this plugin or typewriter-mode
If you need typewriter-mode plugin to do something, please reply to me and I will go to that plugin to raise an issue

### Obsidian version

1.6.3

### OS

Windows

**Comment by ycnmhd** [comment]
I believe this issue must be fixed from `typewriter-mode`'s side.
The plugin should ignore editor instances that are within [lineage view](https://github.com/ycnmhd/obsidian-lineage/blob/8e46ab053304b8d977cd2533bc6dc04650bdd388/src/view/view.ts#L32)

**Comment by calmwaves111** [comment]
Thanks for your reply, I will raise an issue with typewriter-mode
