### ISSUE TITLE
Import from Gingko

### ISSUE THREAD

**Issue by briandbezerra** [ycnmhd/obsidian-lineage#42]
### What would you like to be added?

It would be great to be able to import a Gingko json file or any of the export types from Gingko.

### Why is this feature needed?

The feature will be helpful for folks that are migrating from Gingko to Obsidian.

### Estimated usefulness for plugin users

Useful for some users

**Comment by ycnmhd** [comment]
Importing from gingko has been added as a file context-menu item in [0.6.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.6.0).
(Select one or more json files, and right click on them)
