### ISSUE TITLE
Export only Column

### ISSUE THREAD

**Issue by briandbezerra** [ycnmhd/obsidian-lineage#43]
### What would you like to be added?

Love the plugin. Game changer.

I like to outline screenplays and book ideas in Lineage and then write the actual screenplay or book scenes directly on the child of the outlined scene. Gingko has the option to export the column into one document, which makes it easier for me to export to my Fountain editor of choice.

Alternatively, and I know this might be very niche, you could support .fountain directly on the cards including automatically formatting headers and other screenplay elements. That would be my dream.

Thank you for the plugin.

### Why is this feature needed?

It's needed for those that want to write the final content directly on the Lineage view.

### Estimated usefulness for plugin users

Useful for some users

**Comment by ycnmhd** [comment]
Export column has been added as a card context-menu item in [0.6.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.6.0)
