### ISSUE TITLE
[FR] Expand Cards to Accommodate Text

### ISSUE THREAD

**Issue by julroger2013** [ycnmhd/obsidian-lineage#45]
### What would you like to be added?

I'm noticing that the individual cards on the Gingko interface do not always, when selected, expand to show the entire contents of the card.

I haven't noted yet whether this is true no matter what the contents of the card are, or if it only applies where (as is the case for me), some of the content is other than standard text (callouts, codeblocks, headings, etc.).

Is it possible that it could be made so that the entire contents of a section display when a card is selected?

### Why is this feature needed?

When I'm looking over what I've written so far, it's really helpful to get a larger overview of the card's contents so I can assess any necessary revisions. If I need to "click into" the card to edit it before I can see everything, it makes it more challenging to get a big-picture view of the writing.

### Estimated usefulness for plugin users

Useful for some users

**Comment by ycnmhd** [comment]
Could you provide a markdown file to reproduce this issue?
