### ISSUE TITLE
[FR] Remove section mark in markdown view

### ISSUE THREAD

**Issue by khanhtoan529** [ycnmhd/obsidian-lineage#46]
### What would you like to be added?

These section marks add directly into the markdown file, making it feel really cluttered to read or export. Could you find a way to make this plugin work without these marks?

Actual:
![image](https://github.com/ycnmhd/obsidian-lineage/assets/94975142/d97f38a7-2e2e-4d65-9666-35b79f232036)

Expected result:
![image](https://github.com/ycnmhd/obsidian-lineage/assets/94975142/2593c1b1-79e9-4cb8-b6d1-9088cc005021)

### Why is this feature needed?

This will make the markdown file have a consistent format with other notes.

### Estimated usefulness for plugin users

Useful for the majority of users

**Comment by ycnmhd** [comment]
You can export the document from the view context menu item `export document`. This will remove the comments.
If your document uses headings, you can import it back using the `split card` card context menu item.

Alternatively, you can use the `outline` format to maintain hierarchy.

> Could you find a way to make this plugin work without these marks

Can you suggest an alternative way for the plugin to know the hierarchy of the document?

**Comment by khanhtoan529** [comment]
> Can you suggest an alternative way for the plugin to know the hierarchy of the document?

Unfortunately, I'm not a software developer, so I have no idea about this. But thank you for your response.

Should this FR be closed or open for future enhancement?

**Comment by ycnmhd** [comment]
I can think of three ways, but I'm personally not sure if any of them is better than using plain text comments or the outline format
(1) Use headings: 
- Every group of cards must be under a heading, even if the heading is empty 
- A headless card cannot be a parent
- Depth is limited to 6 levels

(2) Store the `line number` + `line content` in the plugin settings along with the `structure`: 
- The stored structure would break if the document is modified externally
- The structure is not portable
- The structure is not visible in plain markdown
- Computationally heavy
- Data.json file would balloon in size 

(3) Use invisible `<div>` elements:
-  Invisible text is prone to accidental deletion

**Comment by khanhtoan529** [comment]
I think option (3) would be fine because most of us will use `live preview` mode, making the section mark invisible. Additionally, if a user wants to edit that markdown file using Lineage, they will likely rarely edit it in markdown mode. They would primarily use markdown mode to check the file format, not for editing.

**Comment by ycnmhd** [comment]
> They would primarily use markdown mode to check the file format, not for editing

If you don't mind invisible text, you can use this CSS snippet to hide comments
```css
.cm-comment { 
  opacity: 0;
  transition: opacity 200ms;
}

.cm-comment:hover {
  opacity: 1
}
```

**Comment by khanhtoan529** [comment]
It works great. However, I still prefer to be able to remove it instead of hiding it away. Looking for future updates ☺️
