### ISSUE TITLE
[BUG] Cannot switch to outline format

### ISSUE THREAD

**Issue by Quorafind** [ycnmhd/obsidian-lineage#47]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

1. Create a new document.
2. Switch to outline format.
3. Nothing happen.

### What did you expect to happen?

Content can be saved as outline format.

### Relevant console output

![Clip_2024-06-19_09-12-10](https://github.com/ycnmhd/obsidian-lineage/assets/13215013/858565ae-b77c-416c-b48e-7d4706897dab)

### Obsidian version

1.6.3

### OS

Windows

**Comment by ycnmhd** [comment]
This setting is meant for new or first-time `open in lineage` documents.
To switch existing documents, use the view context menu 
![image](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/6e6dd0a8-5435-4384-a582-57259b21edf0)

**Comment by Quorafind** [comment]
Nice! It maybe better to show some notice.
