### ISSUE TITLE
[BUG] Context menu on file would create a blank menu item

### ISSUE THREAD

**Issue by Quorafind** [ycnmhd/obsidian-lineage#48]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

1. Right click on any file(not the folder) in the explorer view.
2. See the blank context menu item between the `Copy Obsidian URL` and `Rename`

![Clip_2024-06-19_09-14-57](https://github.com/ycnmhd/obsidian-lineage/assets/13215013/1e20c8c8-5006-40b8-9226-0e9dc991d22b)

### What did you expect to happen?

Don't show the blank menu item or show correct menu item.

### Relevant console output

![Clip_2024-06-19_09-15-07](https://github.com/ycnmhd/obsidian-lineage/assets/13215013/774fe889-6404-4504-be78-b559b4d825c1)

### Obsidian version

1.6.3

### OS

Windows

**Comment by Quorafind** [comment]
For quickly debugging, the issue occurs at this link: [link](https://github.com/ycnmhd/obsidian-lineage/blob/81e9174b208b26beae8e69add1defbb693c07029/src/obsidian/events/workspace/context-menu-itetms/add-toggle-view-menu-item.ts#L14).

Right click on file item in the file explorer also triggers the file-menu event, resulting in a null leaf. We can check if the leaf is not null before calling menu.addItem.

**Comment by ycnmhd** [comment]
Fixed in 0.6.1
