### ISSUE TITLE
Scrolling & Panning outside Editors like in Canvas plugin

### ISSUE THREAD

**Issue by lifehaschanged** [ycnmhd/obsidian-lineage#49]
### What would you like to be added?

In the Canvas plugin of Obsidian, you can scroll the entire canvas up and down using the mouse wheel without scrolling into the documents.  And if you hold down the spacebar and the left mouse button, you can pan the entire canvas in any direction using the mouse.

### Why is this feature needed?

My fingers always need a bit of a break, and in my experience, mouse scrolling or panning with the thumb key on spacebar is gentler on my fingers than constant keyboard use. 

 It would be really great if you could implement something like this in your Lineage plugin as well.

### Estimated usefulness for plugin users

Useful for many users

**Comment by ycnmhd** [comment]
If I understand correctly, you want
(1) a way to _vertically_ scroll all columns at once using the mouse wheel
(2) hold space and drag to scroll vertically and horizontally
Is this correct?

**Comment by lifehaschanged** [comment]
Yes, thanks.
As for the first part: maybe as an option: It would be great if you could set it up so that a section/document only scrolls when you double click inside it, otherwise not. This way I could scroll the entire column up and down, without scrolling into sections (which have their own scrollbars).
Second part is correct.

**Comment by ycnmhd** [comment]
An alternative way would be to add an `alt+mouse-wheel` setting that can be set to either `scroll column` or `scroll card` 
This would allow the user to alternate between the two behaviors by pressing `alt`

**Comment by N3C2L** [comment]
I like that idea.

**Comment by lifehaschanged** [comment]
> An alternative way would be to add an `alt+mouse-wheel` setting that can be set to either `scroll column` or `scroll card` This would allow the user to alternate between the two behaviors by pressing `alt`

Very Good! Because the Alt key is also right next to the Space key, which I could easily handle with my left hand using the thumb.
