### ISSUE TITLE
markdown heading level based tree structure

### ISSUE THREAD

**Issue by xbeta-zhang** [ycnmhd/obsidian-lineage#50]
### What would you like to be added?

Lineage supports section markers and outliners for the tree structure. 
How about supporting H1, H2, H3, etc., in Markdown files?

### Why is this feature needed?

1. Most notes in Obsidian use native headings, making the Lineage plugin a more commonly used feature.
2. The Obsidian TreeEdit plugin also used this format, but it has been discontinued.  https://github.com/artem-barmin/obsidian-tree-edit.

### Estimated usefulness for plugin users

Useful for Many users

**Comment by ycnmhd** [comment]
(It's worth mentioning that you can import/split a document based on its headings using the card context menu)

**Comment by acook** [comment]
This would mean that it would be easy to export Lineage-edited documents to PDF or Publish without having to first search and replace a bunch and break Lineage integration. 

The number system used in the HTML comments would be nice to use as heading prefixes. This would let Lineage distinguish "structural" headings used for Lineage's nesting layouts from "organizational" headings to be rendered as normal. It should also require minimal changes to Lineage's [parser](https://github.com/ycnmhd/obsidian-lineage/blob/master/src/lib/data-conversion/helpers/delimiter.ts#L6) to pull this off. 

It might be enough to do:

~~~typescript
export const delimiter = (parentNumber: string, index: number) =>
    `\n# ${level(parentNumber, index)}`;
const delimiterRegex = /\s*#\s+((\d\.?)*(\d))[\w\s]/;
~~~

or if you want to get fancy, the number of `#`s in the header could match the nesting level.

**Comment by ycnmhd** [comment]
> it would be easy to export Lineage-edited documents to PDF or Publish without having to first search and replace a bunch and break Lineage integration

To remove the comments, you can use the view context-menu item `export document`
![image](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/152d51a9-dd3b-4026-976d-944a66e295d9)

> break Lineage integration
> or if you want to get fancy, the number of #s in the header could match the nesting level.

If your document uses headings, you can export it and re-import it without breaking it, using the card context-menu item `split card` and then select `headings`. [The parser](https://github.com/ycnmhd/obsidian-lineage/blob/master/src/lib/data-conversion/headings-to-json.ts) uses heading levels to construct the tree
![image](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/68b89d3b-b4f9-4147-96c4-b2f7e2af6436)

Overall, given that you can easily import and export headings-based documents, and unlike the outline format, a headings-based document is the same as a sections-based document, I don't think adding it as a 3rd format provides enough value to justify the complexity it will add to the code and the additional e2e testing burden

**Comment by 0atman** [comment]
If I may, I would like to argue for the headings feature in Lineage. Instead of hijacking this issue, I've added my thoughts to: #86
