### ISSUE TITLE
Can't copy block link

### ISSUE THREAD

**Issue by Bearsaerker** [ycnmhd/obsidian-lineage#54]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

I can't automatically add block links. I'd love to do that because some lineages of my writing link to other trees and if I could link them automatically, it would be very nice. I imagine that it is a bug, because it only doesn't work in the lineage view.

### What did you expect to happen?

Copy block link should work

### Obsidian version

1.6.4

### OS

Linux

**Comment by ycnmhd** [comment]
Can you add steps to reproduce this issue?

**Comment by Bearsaerker** [comment]
I'm in the editing mode of a chunk and I press my hotkey for copying block link and it does nothing. If I switch from lineage view to regular editing view, I can copy the blocklink as it should work.

**Comment by ycnmhd** [comment]
What plugin are you using?
Tested using [this plugin](https://github.com/mgmeyers/obsidian-copy-block-link) and it worked as expected
![2024-06-26_20-35-12](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/2591de9f-7bad-4dd9-bf98-d6eac3b1926f)

Also, cards have a context menu item to copy the block link
![2024-06-26_20-46-31](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/3b634308-6f09-475a-ae44-8e809036ebb0)

**Comment by m95khalil** [comment]
Thank you @ycnmhd for your great efforts. When I try to link a card from within a different one using `[[^]]` a connection is not established. 

It only works using the methodology used in the previous comment: right click the intended block and select `Copy link to block`
