### ISSUE TITLE
Code block not rendered properly in preview mode

### ISSUE THREAD

**Issue by scmanjarrez** [ycnmhd/obsidian-lineage#65]
Hi, first of all, thank you very much for making this plugin, it's an amazing tool!

Is it normal for code block formatting (```) to be lost in lineage mode? 
Edit view:
![image](https://github.com/user-attachments/assets/bfb352de-6f24-44a5-bba1-ab9ec6fc2042)
Normal view:
![image](https://github.com/user-attachments/assets/0222ac3a-8111-4dd1-83b7-8dbd7dc1cb28)

**Comment by ycnmhd** [comment]
Thank you for the bug report. 

I did some debugging and found that the [card component](https://github.com/ycnmhd/obsidian-lineage/blob/81e9174b208b26beae8e69add1defbb693c07029/src/view/components/container/column/components/group/components/card/components/content/content.svelte#L16) is missing the `markdown-rendered` Obsidian CSS class

**Comment by ycnmhd** [comment]
Fixed in 0.6.1
