### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by NewTypo** [ycnmhd/obsidian-lineage#69]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

输入时，文本框会跳出屏幕。

https://github.com/user-attachments/assets/4ffc06b8-e967-4059-b6c5-98af1619de07

### What did you expect to happen?

输入时文本框始终居中

### Obsidian version

1.7.0

### OS

Windows

**Comment by ycnmhd** [comment]
I can't reproduce this bug. It is probably caused by another plugin.
Try disabling plugins that add features to the editor one by one to find out which plugin is causing it.

**Comment by NewTypo** [comment]
Found it, it's the reason for the plugin "Typewriter Mode".

**Comment by NewTypo** [comment]
I've uninstalled the Typewriter Mode plugin, and the world is at peace again.😎
