### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by KuiyueRO** [ycnmhd/obsidian-lineage#7]
Please support the use of this plug-in on mobile devices

**Comment by ycnmhd** [comment]
Can you test version [0.5.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.5.0-dev) on your device? 
I tested it using [this.app.emulateMobile(true)](https://docs.obsidian.md/Plugins/Getting+started/Mobile+development), and it seems to work

**Comment by xbeta-zhang** [comment]
0.5.0 tested on iPhone. View and Edit both OK.
