### ISSUE TITLE
 Don’t display paragraph spacing  in card preview screen

### ISSUE THREAD

**Issue by leslieyu2022** [ycnmhd/obsidian-lineage#70]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

If you set multiple paragraphs when editing a card, but when previewing the card, only one paragraph is displayed，
I'm not sure if that's the way the design is, i.e. you can only fit one paragraph on a card, or if it's just a bug
![CleanShot 2024-09-17 at 21 25 37](https://github.com/user-attachments/assets/24271b6f-1757-428e-b97c-1333746b1bcd
[背景.md](https://github.com/user-attachments/files/17028906/default.md)
)

### What did you expect to happen?

When you edit a card, what you see is what you get

### Obsidian version

0.6.1

### OS

macOS

**Comment by leslieyu2022** [comment]
![CleanShot 2024-09-17 at 21 25 37](https://github.com/user-attachments/assets/a9d352fc-ee06-4f59-a185-dd8ccee0287d)

**Comment by ycnmhd** [comment]
Either **_strict new line_** is enabled in Obsidian settings, or the card has a callout which interferes with [replacing `nbsp` ](https://github.com/ycnmhd/obsidian-lineage/discussions/25#discussioncomment-9574308) (will be fixed in next release)
