### ISSUE TITLE
Style will affect icons in Light Theme

### ISSUE THREAD

**Issue by Moyf** [ycnmhd/obsidian-lineage#77]
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

I'm using light theme and found out that when enabling **Lineage**, many of my buttons will become white and hard to see:
![image](https://github.com/user-attachments/assets/76731108-4b2f-4864-871e-2a05304ccd54)

I checked the sytle:
![image](https://github.com/user-attachments/assets/58661569-d9f2-4a37-b03a-b721fb28bb2a)

After searching, it turns out that styles are added in `main.js` of Lineage:
![image](https://github.com/user-attachments/assets/1af73978-b293-45b3-8c61-85e7678c9d14)

### What did you expect to happen?

I think the color changing of icons should also consider those themes with light background.
Or use var like `--icon-color` to be compatible with different themes.

At least, change the style in `style.css` so that users could modify it easily : )

### Obsidian version

1.8.0

### OS

Windows

**Comment by ycnmhd** [comment]
Thanks for the report. This has been fixed in 0.7.1-beta. 
(if icons are already affected, you need to restart Obsidian)

**Comment by Moyf** [comment]
> Thanks for the report. This has been fixed in 0.7.1-beta. (if icons are already affected, you need to restart Obsidian)

Yes I've updated, and it's fixed. Thank you!
