### ISSUE TITLE
Hello, how about making a button to print with index cards?

### ISSUE THREAD

**Issue by SilmaliTech** [ycnmhd/obsidian-lineage#8]
First of all, I want to say thank you for creating such a great plugin.  thank you.  What do you think about creating a print button on the card?  When you press that button, it will print on a 4x6 index card.  Is it worth considering?

**Comment by ycnmhd** [comment]
I really appreciate your interest in the plugin. However, 🤔 I'm not entirely sure this feature fits its scope. Perhaps it is more suitable as a standalone plugin.
