### ISSUE TITLE
Add an option to always have the active card in the centre of the screen

### ISSUE THREAD

**Issue by michaellw** [ycnmhd/obsidian-lineage#9]
Would it be possible to add an option to always have the active card in the centre of the screen when I navigate the cards?

**Comment by ycnmhd** [comment]
This feature has been implemented in [0.5.0](https://github.com/ycnmhd/obsidian-lineage/releases/tag/0.5.0-dev)

**Comment by michaellw** [comment]
Just updated it, it's so cool.
